# Generated by Django 5.2.16 on 2026-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_department_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment_status',
            field=models.CharField(default='All Cleared (Internal Assessments)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=85.0),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_fee_amount',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_fee_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_result_gpa',
            field=models.FloatField(default=3.8),
        ),
    ]
