# Generated by Django 6.0.6 on 2026-08-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_address_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=4)),
                ('internal_marks', models.FloatField(default=25.0, help_text='Max 30 Marks')),
                ('mid_sem_marks', models.FloatField(default=25.0, help_text='Max 30 Marks')),
                ('final_sem_marks', models.FloatField(default=35.0, help_text='Max 40 Marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student')),
            ],
            options={
                'ordering': ['semester', 'subject_code'],
                'unique_together': {('student', 'semester', 'subject_code')},
            },
        ),
    ]
