# Generated by Django 6.0.6 on 2026-08-04 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_classroomalert_timetableslot'),
        ('students', '0007_exammark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPublishControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('results_published', models.BooleanField(default=True, help_text='Publish Semester Results to Students')),
                ('admit_card_published', models.BooleanField(default=True, help_text='Release Exam Admit Cards to Students')),
                ('exam_name', models.CharField(default='End-Semester Theory Examinations - August 2026', max_length=150)),
                ('academic_session', models.CharField(default='2026-2027', max_length=50)),
                ('exam_center', models.CharField(default='Smart College Main Campus, Examination Block-A', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_publish_controls', to='departments.department')),
            ],
            options={
                'ordering': ['department', 'semester'],
            },
        ),
    ]
