# Generated by Django 6.0.6 on 2026-08-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_exampublishcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFormRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(default='2026-2027', max_length=30)),
                ('semester', models.IntegerField(default=1)),
                ('exam_type', models.CharField(choices=[('REGULAR', 'Regular Semester Examination'), ('BACKLOG', 'Backlog / Re-appear Examination'), ('SPECIAL', 'Special / Supplementary Examination')], default='REGULAR', max_length=20)),
                ('subjects_list', models.TextField(help_text='Comma-separated subject codes/names')),
                ('fee_paid', models.BooleanField(default=True, help_text='Exam Registration Fee Status')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=1200.0, max_digits=8)),
                ('transaction_id', models.CharField(blank=True, default='TXN-ERP-202608', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Submitted - Pending Verification'), ('APPROVED', 'Approved by Exam Controller'), ('REJECTED', 'Rejected / Needs Revision')], default='APPROVED', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_form_registrations', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
