# Generated by Django 6.0.6 on 2026-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_examformregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampublishcontrol',
            name='exam_form_open',
            field=models.BooleanField(default=True, help_text='Open Examination Application Form Fill-Up to Students'),
        ),
    ]
