# Generated by Django 6.0.6 on 2026-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_exampublishcontrol_exam_form_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampublishcontrol',
            name='marks_entry_open',
            field=models.BooleanField(default=True, help_text='Open Faculty Exam Marks Entry & Update Portal'),
        ),
    ]
