# Generated by Django 5.2.16 on 2026-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_department_alter_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='office_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
