# Generated by Django 6.0.6 on 2026-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_office_location_faculty_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/'),
        ),
    ]
