# Generated by Django 6.0.6 on 2026-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
