# Generated by Django 6.0.6 on 2026-08-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXAM_CONTROLLER', 'Examination Controller'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
