# Generated by Django 6.0.6 on 2026-07-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('faculty', '0005_faculty_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('room_number', models.CharField(help_text='e.g. Room 302, LH-01', max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('alert_type', models.CharField(choices=[('ROOM_CHANGE', 'Room Change'), ('CANCELLATION', 'Class Cancelled'), ('SCHEDULE_CHANGE', 'Schedule Shift'), ('URGENT', 'Urgent Notice'), ('INFO', 'General Info')], default='INFO', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High / Urgent'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('message', models.TextField()),
                ('created_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_faculty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_alerts', to='faculty.faculty')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_alerts', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], default='MONDAY', max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(default='Room 101', max_length=50)),
                ('semester_or_year', models.CharField(blank=True, default='Semester 1', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='departments.department')),
                ('faculty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='faculty.faculty')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
